-- Add foreign key for user_id in messages table
alter table public.messages
  drop constraint if exists messages_user_id_fkey,
  add constraint messages_user_id_fkey 
  foreign key (user_id) 
  references auth.users(id);

-- Make sure the recipient_id foreign key is properly set
alter table public.messages
  drop constraint if exists messages_recipient_id_fkey,
  add constraint messages_recipient_id_fkey 
  foreign key (recipient_id) 
  references auth.users(id);

-- Recreate the messages table with proper constraints if needed
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_id uuid references auth.users(id) not null,
  user_email text not null,
  image_url text,
  recipient_id uuid references auth.users(id)
);

-- Make sure RLS is enabled
alter table public.messages enable row level security;

-- Recreate the messages policies
drop policy if exists "Allow users to read messages" on public.messages;
create policy "Allow users to read messages"
  on public.messages
  for select
  to authenticated
  using (
    recipient_id is null -- public messages
    or user_id = auth.uid() -- sent by user
    or recipient_id = auth.uid() -- received by user
  );

-- Allow users to insert their own messages
drop policy if exists "Allow authenticated users to insert their own messages" on public.messages;
create policy "Allow users to insert messages"
  on public.messages
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- Enable realtime for messages
alter publication supabase_realtime add table messages;
