-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_id uuid references auth.users(id) not null,
  user_email text not null
);

-- Set up row level security
alter table public.messages enable row level security;

-- Create policy to allow authenticated users to read all messages
create policy "Allow authenticated users to read messages"
  on public.messages
  for select
  to authenticated
  using (true);

-- Create policy to allow authenticated users to insert their own messages
create policy "Allow authenticated users to insert their own messages"
  on public.messages
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Enable realtime
alter publication supabase_realtime add table messages;
